### ISSUE TITLE
add an env variable for XS

### ISSUE THREAD

**Issue by avereha** [p5pclub/http-headers-fast-xs#8]
Called  PERL_HTTP_HEADERS_FAST_XS. That variable will control if we load the XS version of the module or not.

**Comment by stevenl** [comment]
Implemented in branch `stevenl/pp_or_xs`.

This is just a simple solution that makes the decision once when the XS module is loaded. At this stage, it doesn't solve the original motivation for this ticket, which is to allow using both PP and XS within the same script. I think that will require changes in HTTP::Headers::Fast itself.

**Comment by xsawyerx** [comment]
I'm sorry I didn't read this comment before. I implemented it too and put it in master. Sorry @stevenl. :/

I did, however, put it in `Fast.pm` instead of `Fast/XS.pm`.

On the other hand, we share the same implementation. :)

**Comment by stevenl** [comment]
I've now done a second take at this. This time I've done it so that the decision is made during construction. This allows us to have both PP and XS modules loaded and being able to decide which to use during runtime.

To use the XS implementation it requires that the objects be of type 'HTTP::Headers::Fast::XS', which is a subtype of 'HTTP::Headers::Fast'. Unfortunately this breaks some tests, which I'm not sure how to resolve at this stage.

**Comment by xsawyerx** [comment]
That's pretty nifty!

However, I can tell you that this will break several pieces of code and tests that check for `HTTP::Headers::Fast` and not optionally `HTTP::Headers::Fast::XS`.

We could do this, but it would force frameworks to update their code. I can tell you last time (when `HTTP::Headers::Fast` was introduced) it broke Dancer2 and we had to update it immediately. That wasn't fun. :)

**Comment by stevenl** [comment]
I was afraid of something like that.

Anyway I've resolved the failing tests. HTTP::Headers::Fast had its own implementation of isa() which checks specifically for `ref($self) eq 'HTTP::Headers'`. I got it to check $self against HTTP::Headers::Fast in the same way. Is this the sort of thing you're talking about?

**Comment by tsee** [comment]
On 08/10/2015 10:27 PM, Steven Lee wrote:

> I was afraid of something like that.
> 
> Anyway I've resolved the failing tests. HTTP::Headers::Fast had its own
> implementation of isa() which checks specifically for |ref($self) eq
> 'HTTP::Headers'|. I got it to check $self against HTTP::Headers::Fast in
> the same way. Is this the sort of thing you're talking about?

Just FTR, that sort of thing is pretty terrible. Just think of the poor 
object oriented kittens!

--Steffen

PS: If two such modules are really entirely behaving the same, then it 
ought to be possible to do one of two safe-ish things: Fully override 
everything in a subclass, or replace all methods/functions in the 
original class from the ::XS (or ::Fast) module. Why wouldn't those work 
here?

**Comment by stevenl** [comment]
I didn't like the way isa() works here either, but that's how HTTP::Headers::Fast does it, which is why the tests broke in the first place. I didn't want to change that because I don't understand why they've done it that way.

Otherwise the solution was as you suggested: override everything in a XS subclass. That except for one point, which is to be able to construct the XS objects from the parent PP class to allow for a transparent transition to the XS implementation without having to call the constructor from the XS class.

I guess a possible next step is to declare HTTP::Headers::Fast a subclass of HTTP::Headers and get rid of its isa() method.
